language: python

python:
  - "3.6"

install:
  - pip install -Ur requirements.txt

cache:
  bundler: true
  directories:
    - $HOME/.pytest_cache
    - $HOME/.cache/pip
    - $HOME/docker
    - $HOME/.wdm/drivers

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

addons:
  apt:
    packages:
      - net-tools

services:
  - docker

script:
  - export HOST_IP=$(ifconfig docker0 | awk -F"[:, ]+" '/inet/ {print $4}')
  - echo "$DOCKER_PAS" | docker login --username "$DOCKER_USER" --password-stdin
  - docker-compose -f ./selenium-grid/docker-compose.yml up -d
  - . ./selenium-grid/wait-for-grid.sh
  - pytest -v -s
  - docker-compose -f ./selenium-grid/docker-compose.yml down